site_name: Netsweeper Docs
site_description: Netsweeper guides
site_url: https://ns-wki.eduhost.org.uk
site_author: Adam Bird
theme:
  name: material
  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark Mode
    primary: green
    accent: deep purple

  # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light Mode
    primary: blue
    accent: green
plugins:
  - search
  - callouts
  - awesome-nav:
      filename: .nav.yml
markdown_extensions:
- attr_list
- nl2br
- admonition
- pymdownx.details
- pymdownx.superfences
extra_css:
  - stylesheets/extra.css